url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Luke Arcamo" # the name of your site, e.g. ACME Corp.
description: "The work of an artist, programmer, engineer, and bookworm."

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      excerpt_separator: "<!--split-->"
